epam/NGB

.travis.yml
README.md
server/catgenome/build.gradle
server/ngb-cli/build.gradle

It seems very handy to view current status of a code coverage for a repository and for each PR
* Added jacoco XML reports to gradle configuration
* Added CodeCov integration to travis configuration

Codecov integration

---

client/client/app/shared/components/ngbMainSettings/ngbMainSettingsDlg/ngbMainSettingsDlg.tpl.html
client/client/dataServices/local/defaultData.js
client/client/modules/render/tracks/vcf/index.js
client/client/modules/render/tracks/vcf/internal/renderer/index.js
client/client/modules/render/tracks/vcf/internal/renderer/placeholderRenderer.js

This PR copies #17 from `2.4-LTS` to current development branch

VCF tracks now have a setting for variants displaying range (#17)

---

docs/md/installation/binaries.md
docs/md/installation/standalone.md
server/catgenome/profiles/desktop/catgenome.properties
server/catgenome/profiles/dev/catgenome.properties
server/catgenome/profiles/h2/test-catgenome.properties
server/catgenome/profiles/jar/catgenome.properties
server/catgenome/profiles/postgres/test-catgenome.properties
server/catgenome/profiles/release/catgenome.properties
server/catgenome/profiles/staging/catgenome.properties
server/catgenome/src/main/java/com/epam/catgenome/constant/MessagesConstants.java
server/catgenome/src/main/java/com/epam/catgenome/entity/BaseEntity.java
server/catgenome/src/main/java/com/epam/catgenome/entity/index/FeatureIndexEntry.java
server/catgenome/src/main/java/com/epam/catgenome/entity/index/VcfIndexEntry.java
server/catgenome/src/main/java/com/epam/catgenome/manager/FeatureIndexManager.java
server/catgenome/src/main/java/com/epam/catgenome/manager/vcf/VcfManager.java
server/catgenome/src/main/java/com/epam/catgenome/util/DiskBasedList.java
server/catgenome/src/main/resources/catgenome-messages.properties
server/catgenome/src/test/java/com/epam/catgenome/manager/vcf/VcfManagerTest.java
server/catgenome/src/test/java/com/epam/catgenome/util/DiskBasedListTest.java

This PR copies #16  from current development branch to 2.4-LTS

Fix for OutOfMemory exception when registering 1Gb+ VCF files (#16) - to LTS

---

client/client/app/components/ngbProjectInfoPanel/ngbProjectInfo/ngbVariantDensityDiagram/ngbVariantDensityDiagram.controller.js
client/client/app/components/ngbProjectInfoPanel/ngbProjectInfo/ngbVariantQualityDiagram/ngbVariantQualityDiagram.controller.js
client/client/app/components/ngbProjectInfoPanel/ngbProjectInfo/ngbVariantTypeDiagram/ngbVariantTypeDiagram.controller.js
client/client/app/components/ngbProjectInfoPanel/ngbProjectInfoPanel.controller.js
client/client/app/components/ngbVariantsTablePanel/index.js
client/client/app/components/ngbVariantsTablePanel/ngbVariantsLoadingIndicator/index.js
client/client/app/components/ngbVariantsTablePanel/ngbVariantsLoadingIndicator/ngbVariantsLoadingIndicator.component.js
client/client/app/components/ngbVariantsTablePanel/ngbVariantsLoadingIndicator/ngbVariantsLoadingIndicator.controller.js
client/client/app/components/ngbVariantsTablePanel/ngbVariantsLoadingIndicator/ngbVariantsLoadingIndicator.scss
client/client/app/components/ngbVariantsTablePanel/ngbVariantsLoadingIndicator/ngbVariantsLoadingIndicator.tpl.html
client/client/app/components/ngbVariantsTablePanel/ngbVariantsTable/ngbVariantsTable.controller.js
client/client/app/components/ngbVariantsTablePanel/ngbVariantsTablePaginate/ngbVariantsTablePaginate.controller.js
client/client/app/shared/components/ngbGoldenLayout/ngbViewActions/ngbViewActions.constant.js
client/client/app/shared/components/ngbGoldenLayout/ngbViewActions/ngbViewActions.tpl.html
client/client/app/shared/projectContext/index.js
client/client/dataServices/project/project-data-service.js
server/catgenome/profiles/desktop/catgenome.properties
server/catgenome/profiles/dev/catgenome.properties
server/catgenome/profiles/jar/catgenome.properties
server/catgenome/profiles/release/catgenome.properties
server/catgenome/src/main/java/com/epam/catgenome/constant/MessagesConstants.java
server/catgenome/src/main/java/com/epam/catgenome/dao/index/FeatureIndexDao.java
server/catgenome/src/main/java/com/epam/catgenome/manager/FeatureIndexManager.java
server/catgenome/src/main/resources/catgenome-messages.properties

This PR copies #25 from current development branch to 2.4-LTS

Limit for lucene index size for /filter and /group API requests (#25) - to LTS

---

server/catgenome/src/main/java/com/epam/catgenome/manager/wig/BedGraphProcessor.java

According to issue #27 currently we can't show bedGraph file if name of chromosomes into the reference file and the bedGraph file differ.
This PR leads to changes that fix it. 
BedGraphProcessor class was changed in order to fetch the real name of the chromosome when  a bedGraph track has requested. 
Try to use a reference with name of chromosomes in a way like 1, 2, 3, 4 ... with a BedGraph with a chromosome name pattern like chr1 chr2 chr3 ... 
It should work correctly.

Fix for issue #27

---

client/client/app/shared/components/ngbMainSettings/ngbMainSettings.controller.js
client/client/app/shared/components/ngbMainSettings/ngbMainSettingsDlg/ngbMainSettingsDlg.tpl.html
client/client/dataServices/local/local-data-service.js
client/client/modules/render/core/track/cachedTrack/cachedTrackRenderer.js
client/client/modules/render/core/track/track.js
client/client/modules/render/tracks/gene/geneConfig.js
client/client/modules/render/tracks/gene/index.js
client/client/modules/render/tracks/gene/internal/renderer/geneRenderer.js
client/client/modules/render/tracks/reference/index.js
client/client/modules/render/tracks/reference/referenceConfig.js
client/client/modules/render/tracks/seg/index.js
client/client/modules/render/tracks/seg/segConfig.js
client/client/modules/render/tracks/seg/segRenderer.js
client/client/modules/render/tracks/vcf/index.js
client/client/modules/render/tracks/vcf/internal/drawing/vcfRenderer.js
client/client/modules/render/tracks/vcf/internal/renderer/collapsed/vcfRenderer.js
client/client/modules/render/tracks/vcf/vcfConfig.js
client/client/modules/render/tracks/wig/index.js
client/client/modules/render/tracks/wig/wigConfig.js
client/client/modules/render/tracks/wig/wigRenderer.js

Fix for #30
Added "Show central line" option to General tab of Settings
Added vertical line through all tracks
1. Open different tracks 
2. Show vertical line through all tracks
3. Open General tab of Settings
4. Uncheck "Show central line" option 
5. Doesn't show vertical line

Added vertical line through all tracks

---

client/client/app/shared/components/ngbMainSettings/ngbMainSettingsDlg/ngbMainSettingsDlg.tpl.html
client/client/dataServices/local/defaultData.js
client/client/modules/render/tracks/bam/index.js
client/client/modules/render/tracks/bam/internal/cache/bamCacheService.js
client/client/modules/render/tracks/bam/internal/transformers/bamReadsCoverageTransformer.js

Fix for issue #38
*What was changed in the system to accomplish the task*
Added "Allele frequency threshold" setting 
*How to check that a task is accomplished, what user shall do to check it*
Open BAM
Change "Allele frequency threshold" setting to NGB global settings: "Settings" -> "Alignments" -> "Coverage Options"
BAM track shall be redrawn

Introduce allele frequency thresholds settings for BAM coverage

---

client/client/app/components/ngbTracksView/managers/ngbTracksView.camera.manager.js
client/client/modules/render/core/track/track.js

Screenshot feature fix (according to #52 )
* Open any tracks, navigate to chromosome
* Click screenshot button
* Image should be downloaded with correct track's visualization
~~- [ ] Unit tests are provided~~
~~- [ ] Integration tests are provided (if CLI/API was changed)~~
~~- [ ] Documentation is updated~~

Screenshot feature fixed

---

client/client/app/components/ngbVariantsTablePanel/ngbVariantsTableColumn/ngbVariantsTableColumn.tpl.html

Fix for `Sort drop down menu contents in alphabetical order` withi issue: https://github.com/epam/NGB/issues/40
Drop down menu sorted in alphabetical order
Check that Variations->Drop down menu is sorted

Sort variable columns drop down menu contents in alphabetical order

---

client/client/app/shared/components/ngbGoldenLayout/ngbCoordinates/ngbCoordinates.controller.js

Fix for issue #58
Updated _parseCoordinates function to extend coordinates formats
Type coordinates.
Allowed formats at the moment are following:
`chromosome:  position`
`chromosome:  start - end`
`chromosome:`
`position`
`start - end`

Extended allowed location formats

---

client/client/app/app.controller.js

fix for #125 
Added window.opener support 
1. open NGB in new window
2. try communicate with NGB using JSApi

window.opener support for JSApi

---

client/client/app/app.controller.js

fix for #125
Fix postMessage looping
Added check if NGB is opened in Iframe
1. open NGB in new window  (not iFrame)
2. try communicate with NGB using JSApi. NGB should not fell in infinite query looping.

Window opener support for js api

---

client/client/app/shared/services/api.service.js

Fix for issue #133
JS API response changed
Some methods like loadTracks do respond on RPC call
Demonstration example
Example of a JS API usage is available at NGB/docs/md/user-guide/embedding-js-demo.html

fixed no response bug

---

.travis.yml
publish.sh

The publish.sh script is changed to allow automatic creation of the docker image from develop branch.
publish.sh was changed - added if block with push to dockerhub from "develop" branch added
The image with "dev" suffix should be published on the [dockerhub](https://hub.docker.com/r/lifescience/ngb/tags/)

Automatic Docker image creation via Travis

---

server/catgenome/src/main/resources/application.properties

This PR fixes index cache property name in application.properties.
Changed cache property name.

Fix index cache property application

---

client/client/app/components/ngbDataSets/internal/ngbDataSetsTerminalNode.tpl.html
client/client/app/components/ngbDataSets/internal/utilities.js
client/client/app/components/ngbDataSets/ngbDataSets.controller.js
client/client/app/components/ngbProjectInfoPanel/ngbProjectInfo/ngbProjectSummary/ngbProjectSummary.controller.js
client/client/app/components/ngbTracksView/ngbTrack/ngbTrack.controller.js
client/client/app/components/ngbTracksView/ngbTrack/ngbTrack.tpl.html
client/client/app/shared/components/ngbMainToolbar/ngbOpenFile/ngbOpenFile.controller.js

Rename file in current session - fixed

---

.travis.yml
singularity/build_image.sh
singularity/ngb.singularity
singularity/setup_environment.sh

This is an update to #224. Now Singularity 2.4 is supported as well.
To specify Singularity environment version - `SINGULARITY_ENV_VERSION` variable shall be set

NGB Singularity - support both 2.4 and 3.0

---

server/catgenome/src/main/java/com/epam/catgenome/controller/wig/WigController.java
server/catgenome/src/main/java/com/epam/catgenome/manager/wig/BedGraphProcessor.java
server/catgenome/src/main/java/com/epam/catgenome/manager/wig/FacadeWigManager.java
server/catgenome/src/main/java/com/epam/catgenome/manager/wig/WigSecurityService.java
server/catgenome/src/test/java/com/epam/catgenome/manager/wig/BedGraphProcessorTest.java
server/catgenome/src/test/java/com/epam/catgenome/manager/wig/WigProcessorTest.java
server/ngb-cli/src/main/java/com/epam/ngb/cli/entity/BiologicalDataItemFormat.java
server/ngb-cli/src/main/java/com/epam/ngb/cli/manager/command/handler/http/GrantPermissionHandler.java

This PR makes it possible to register and view bedGraph files from S3 buckets

bedgraph s3 file support

---

server/ngb-cli/src/main/java/com/epam/ngb/cli/constants/MessageConstants.java
server/ngb-cli/src/main/java/com/epam/ngb/cli/entity/AclClass.java
server/ngb-cli/src/main/java/com/epam/ngb/cli/entity/PermissionGrantRequest.java
server/ngb-cli/src/main/java/com/epam/ngb/cli/entity/UserContext.java
server/ngb-cli/src/main/java/com/epam/ngb/cli/manager/command/handler/http/AbstractHTTPCommandHandler.java
server/ngb-cli/src/main/java/com/epam/ngb/cli/manager/command/handler/http/DatasetListHandler.java
server/ngb-cli/src/main/java/com/epam/ngb/cli/manager/command/handler/http/GrantPermissionHandler.java
server/ngb-cli/src/main/java/com/epam/ngb/cli/manager/command/handler/http/PrintPermissionsHelper.java
server/ngb-cli/src/main/java/com/epam/ngb/cli/manager/command/handler/http/SearchHandler.java
server/ngb-cli/src/test/java/com/epam/ngb/cli/AbstractCliTest.java
server/ngb-cli/src/test/java/com/epam/ngb/cli/TestHttpServer.java
server/ngb-cli/src/test/java/com/epam/ngb/cli/manager/command/handler/http/DatasetListHandlerTest.java
server/ngb-cli/src/test/java/com/epam/ngb/cli/manager/command/handler/http/SearchHandlerTest.java

This PR contains fixes for issues: https://github.com/epam/NGB/issues/249, https://github.com/epam/NGB/issues/248, https://github.com/epam/NGB/issues/247

Fixes for permission viewing

---

client/client/app/components/ngbDataSets/internal/ngbPermissionsForm/ngbPermissionsForm.controller.js
client/client/dataServices/permissions/permissions-data-service.js

This PR fixes #257 
Permission DELETE request's URI component has been encoded.

Fix for IDP groups deletion in permissions management form

---

client/client/app/shared/components/ngbUserManagement/ngbUserManagementDlg/ngbRoleForm/ngbRoleForm.controller.js
client/client/app/shared/components/ngbUserManagement/ngbUserManagementDlg/ngbRoleForm/ngbRoleForm.tpl.html
client/client/app/shared/components/ngbUserManagement/ngbUserManagementDlg/ngbUserForm/ngbUserForm.controller.js
client/client/app/shared/components/ngbUserManagement/ngbUserManagementDlg/ngbUserForm/ngbUserForm.tpl.html
client/client/app/shared/components/ngbUserManagement/ngbUserManagementDlg/ngbUserRoleForm.service.js
client/client/dataServices/role/role-data-service.js
client/client/dataServices/user/user-data-service.js

This PR fixes #261 
Errors are now being displayed in Create/Edit user/group/role forms.
Try to add a user that already exists.

Error handling for the user management forms

---

client/client/app/components/ngbDataSets/internal/ngbDataSetsParentNode.tpl.html
client/client/app/components/ngbDataSets/internal/ngbDataSetsTerminalNode.tpl.html
client/client/app/components/ngbDataSets/internal/utilities.js
client/client/app/components/ngbDataSets/ngbDataSets.controller.js
client/client/app/components/ngbDataSets/ngbDataSets.scss

Issue #201 
* Specified pattern is searched along the entire dataSet name/file name (not only from the beggining)
* If a dataSet contains files that match the pattern, dataSet's content is expanded
* Names of dataSets/files that match the pattern are highlighted
Try to search files in "Datasets" panel and see how appearance has changed

Improvements for the search field in "Datasets" panel (#201):
