client/client/app/shared/components/ngbMainSettings/ngbMainSettingsDlg/ngbMainSettingsDlg.tpl.html, client/client/dataServices/local/defaultData.js, client/client/modules/render/tracks/vcf/index.js, client/client/modules/render/tracks/vcf/internal/renderer/index.js, client/client/modules/render/tracks/vcf/internal/renderer/placeholderRenderer.js
This PR fixes low performance while loading VCF tracks, described in #14 
* New global setting added for VCF tracks - 'maximum variants range'. 
1. Open global settings form, select 'VCF' tab
2. Observe value for maximum variants displaying range
3. Open VCF track(s), select range greater then current maximum one
4. 'Zoom in to see variants' message should be displayed on tracks instead of data
5. Zoom in to fit current maximum range
6. After data loading finished, variants should be displayed
7. Open global setting form, select 'VCF' tab, change value for maximum range
8. Repeat steps 3-6
- [-] Unit tests are provided
- [-] Integration tests are provided (if CLI/API was changed)
- [-] Documentation is updated
=> VCF tracks now have a setting for variants displaying range

docs/md/installation/binaries.md, docs/md/installation/standalone.md, server/catgenome/profiles/desktop/catgenome.properties, server/catgenome/profiles/dev/catgenome.properties, server/catgenome/profiles/h2/test-catgenome.properties, server/catgenome/profiles/jar/catgenome.properties, server/catgenome/profiles/postgres/test-catgenome.properties, server/catgenome/profiles/release/catgenome.properties, server/catgenome/profiles/staging/catgenome.properties, server/catgenome/src/main/java/com/epam/catgenome/constant/MessagesConstants.java, server/catgenome/src/main/java/com/epam/catgenome/entity/BaseEntity.java, server/catgenome/src/main/java/com/epam/catgenome/entity/index/FeatureIndexEntry.java, server/catgenome/src/main/java/com/epam/catgenome/entity/index/VcfIndexEntry.java, server/catgenome/src/main/java/com/epam/catgenome/manager/FeatureIndexManager.java, server/catgenome/src/main/java/com/epam/catgenome/manager/vcf/VcfManager.java, server/catgenome/src/main/java/com/epam/catgenome/util/DiskBasedList.java, server/catgenome/src/main/resources/catgenome-messages.properties, server/catgenome/src/test/java/com/epam/catgenome/manager/vcf/VcfManagerTest.java, server/catgenome/src/test/java/com/epam/catgenome/util/DiskBasedListTest.java
Fix for the Issue https://github.com/epam/NGB/issues/14
Loading VCF files up to 500Mb leads to OutOfMemory exception. That's because during processing loaded VCF `VcfIndexEntry`s for each contig are stored in the memory.
`ArrayList` collection for storing `VcfIndexEntry` is replaced by disk-based implementation: `DiskBasedList` (could be adapted to `java.util.List`). `DiskBasedList` has in-memory buffer of given length and if the buffer is overfilled, it will be spilled to temp file in the temp directory, from which items will be read during iteration. 
Items, which stored in `DiskBasedList` are serialized/deserialized by `java.io.Object*Streams` and deflated/inflated by *Snappy* lib (from *htsjdk* dependency). It leads to about x1.7 slowdown (compared to the case we have enough RAM).
If …
=> Fix for OutOfMemory exception when registering 1Gb+ VCF files

docs/md/cli/command-reference.md
**Issue: https://github.com/epam/NGB/issues/21**
NGB allows to use specified value for reference sequence name through `-n (--name) [value]` option. But if one registers file using number as name, file registration shall not work with number name reference.
The general commands description was supplemented by "Specified value for reference sequence name mustn't be a number (it will be recognized as ID)".
=> Description refinement of reference name at registration reference sequence

client/client/app/components/ngbProjectInfoPanel/ngbProjectInfo/ngbVariantDensityDiagram/ngbVariantDensityDiagram.controller.js, client/client/app/components/ngbProjectInfoPanel/ngbProjectInfo/ngbVariantQualityDiagram/ngbVariantQualityDiagram.controller.js, client/client/app/components/ngbProjectInfoPanel/ngbProjectInfo/ngbVariantTypeDiagram/ngbVariantTypeDiagram.controller.js, client/client/app/components/ngbProjectInfoPanel/ngbProjectInfoPanel.controller.js, client/client/app/components/ngbVariantsTablePanel/index.js, client/client/app/components/ngbVariantsTablePanel/ngbVariantsLoadingIndicator/index.js, client/client/app/components/ngbVariantsTablePanel/ngbVariantsLoadingIndicator/ngbVariantsLoadingIndicator.component.js, client/client/app/components/ngbVariantsTablePanel/ngbVariantsLoadingIndicator/ngbVariantsLoadingIndicator.controller.js, client/client/app/components/ngbVariantsTablePanel/ngbVariantsLoadingIndicator/ngbVariantsLoadingIndicator.scss, client/client/app/components/ngbVariantsTablePanel/ngbVariantsLoadingIndicator/ngbVariantsLoadingIndicator.tpl.html, client/client/app/components/ngbVariantsTablePanel/ngbVariantsTable/ngbVariantsTable.controller.js, client/client/app/components/ngbVariantsTablePanel/ngbVariantsTablePaginate/ngbVariantsTablePaginate.controller.js, client/client/app/shared/components/ngbGoldenLayout/ngbViewActions/ngbViewActions.constant.js, client/client/app/shared/components/ngbGoldenLayout/ngbViewActions/ngbViewActions.tpl.html, client/client/app/shared/projectContext/index.js, client/client/dataServices/project/project-data-service.js, server/catgenome/profiles/desktop/catgenome.properties, server/catgenome/profiles/dev/catgenome.properties, server/catgenome/profiles/release/catgenome.properties, server/catgenome/src/main/java/com/epam/catgenome/constant/MessagesConstants.java, server/catgenome/src/main/java/com/epam/catgenome/dao/index/FeatureIndexDao.java, server/catgenome/src/main/java/com/epam/catgenome/manager/FeatureIndexManager.java, server/catgenome/src/main/java/com/epam/catgenome/manager/vcf/VcfManager.java, server/catgenome/src/main/resources/catgenome-messages.properties
This pull request provides a solution for performance of /filter and /group requests for large (more than 500Mb) VCF files
For large VCF files Lucene index becomes too large and some requests take too long. To resolve this issue, we suggest to check Lucene index size before making request to it and cancel requests if index is too large.
,Appropriate changes are done to FeatureIndexDao and application property "lucene.index.max.size.grouping" is added to catgenome.properties to control max index size. Default value is 4Gb. 
Register 500Mb VCF file and check that /group request doesn't return any data and /filter request doesn't return  as totalPagesCount value.
=> Limit for lucene index size for /filter and /group API requests

client/client/app/shared/components/ngbMainSettings/ngbMainSettingsDlg/ngbMainSettingsDlg.tpl.html
Fix for issue #32
Added checking the "maximum variants range(bp)" field
1. Open NGB
2. Click "SETTINGS" icon
3. Click "VCF" tab
4. Enter negative number in "maximum variants range(bp)" field
5. Click "SAVE" button
6. Expected: warning message
=> Fix for negative number in "maximum variants range"

client/client/dataServices/wig/wig-data-service.js
Fix for issue #33
Added errors handling
1.Rregister .bw file, in this file should be absent data for one or more chromosome
2. Add this file in dataset
3. Open dataset
4. Open browser console
5. Select chromosome which absent in .bw
=> Fix stuck loading indicator for bigWig/bedGraph tracks

README.md
Our users sometimes get lost when searching for prebuilt binaries sources. This is not covered directly in the documentation
Added `release` and `develop` binaries locations to root `README.md`
=> Distribution sources description

client/client/app/shared/components/ngbMainToolbar/ngbOpenFile/ngbOpenFileFromUrl/ngbOpenFileFromUrl.controller.js, client/client/app/shared/components/ngbMainToolbar/ngbOpenFile/ngbOpenFileFromUrl/ngbOpenFileFromUrl.tpl.html
Fix for issue #39 
Added check  file extension.
We open BED/GFF(GFF3)/GTF/CRAM files
=> Fix "Open from URL" to open all supported file types

client/package.json, client/webpack.config.babel/webpack.plugins.js
Fix for issue #63
Removed the "favicons-webpack-plugin" package.
Changed the favicon adding logic
1. Run ‘npm install’
2. Open ‘node_modules’ folder 
3. This folder should not contain ‘phantomjs-prebuilt’  folder.
Check favicon:
1. Open NGB
2. Tab of the browser contains favicon
=> PhantomJS causes GUI build to fail in certain cases #63

client/client/app/assets/scss/base/buttons.scss, client/client/app/shared/components/widgets/collapsiblePanel/collapsiblePanel.tpl.html
**Fix for Issue: https://github.com/epam/NGB/issues/56**
Expand symbol in variation info was moved to left
Open a variation info tab
=> Moved expand symbol in variation info to left

server/catgenome/src/main/java/com/epam/catgenome/manager/gene/GffManager.java
In order to build SV visualization we fetch the transcripts data from Ensembl and then for each transcript query Uniprot. If transcript isn't found in Uniprot transcript processing stops with exception. If such exception occurs at first transcript entry, we won't get any data for visualization at all.
If Uniprot entry for a transcript isn't found or any exception occurs, we proceed with the next transcript.
Check that SV visualization for ALK gene is built correctly.
=> Transcript fetch won't fail if any of entries isn't found in Uniprot DB

client/client/modules/render/tracks/bam/internal/renderer/features/coverageRenderer.js, client/client/modules/render/tracks/bam/internal/transformers/bamReadsCoverageTransformer.js
Fix for issue #61
Reference letters in BAM coverage graph display gray color
Open BAM track.
If there are mismathes and a letter at this position are the same as in reference, then it displayed by gray color.
=> Display reference letters in BAM coverage graph using gray color #61

client/client/app/components/ngbVariantPanel/ngbVariantPanel.controller.js, client/client/app/components/ngbVariantPanel/ngbVariantPanel.tpl.html, client/client/app/shared/components/ngbVariantDetails/index.js, client/client/app/shared/components/ngbVariantDetails/ngbVariantDbSnp/ngbVariantDbSnp.component.js, client/client/app/shared/components/ngbVariantDetails/ngbVariantDbSnp/ngbVariantDbSnp.controller.js, client/client/app/shared/components/ngbVariantDetails/ngbVariantDbSnp/ngbVariantDbSnp.scss, client/client/app/shared/components/ngbVariantDetails/ngbVariantDbSnp/ngbVariantDbSnp.service.js, client/client/app/shared/components/ngbVariantDetails/ngbVariantDbSnp/ngbVariantDbSnp.tpl.html, client/client/app/shared/components/ngbVariantDetails/ngbVariantDetails.constant.js, client/client/dataServices/externaldb/externaldb-data-service.js, server/catgenome/src/main/java/com/epam/catgenome/controller/vo/externaldb/NCBIClinVarVO.java, server/catgenome/src/main/java/com/epam/catgenome/controller/vo/externaldb/NCBIVariationVO.java, server/catgenome/src/main/java/com/epam/catgenome/manager/externaldb/ncbi/NCBIClinVarManager.java, server/catgenome/src/main/java/com/epam/catgenome/manager/externaldb/ncbi/NCBIShortVarManager.java, server/catgenome/src/test/java/com/epam/catgenome/manager/externaldb/NCBIShortVarManagerTest.java
Fix for issue #57 
Additional tab 'DbSNP' appeared in Variation panel if rsId in variation is specified
Open a variation info panel (variation's rsId should be available to see tab)
=> Automatic downloading of variation info from db snp

client/client/app/components/ngbTracksView/ngbTrack/ngbTrack.tpl.html
Fix for issue #93 
Added a tooltip with a full file name when hovering it
Users see the full file name when they mouse over the track name on a track header.
=> Show full file name on a track header #93

docs/md/cli/command-reference.md, server/catgenome/src/main/java/com/epam/catgenome/manager/reference/ReferenceGenomeManager.java, server/catgenome/src/test/java/com/epam/catgenome/manager/bed/BedManagerTest.java, server/catgenome/src/test/java/com/epam/catgenome/manager/reference/ReferenceGenomeManagerTest.java, server/catgenome/src/test/java/com/epam/catgenome/manager/vcf/VcfManagerTest.java
Support for  VCF files as genomic annotations 
#118
This PR enables attaching VCF files as annotations to reference genomes using ngb-cli "add_ann|an" command
API method for adding annotation files now accepts GFF, GTF, BED and VCF files
- register reference file
- attach annotation: "ngb add_ann ref_name /path/to/file.vcf"
- on UI open dropdown menu for annotation files and ensure, that vcf file is present
=> Support for VCF files as annotations

server/catgenome/build.gradle, server/catgenome/src/main/java/com/epam/catgenome/exception/S3ReadingException.java, server/catgenome/src/main/java/com/epam/catgenome/manager/FileManager.java, server/catgenome/src/main/java/com/epam/catgenome/manager/bam/BamHelper.java, server/catgenome/src/main/java/com/epam/catgenome/manager/bam/BamManager.java, server/catgenome/src/main/java/com/epam/catgenome/manager/bed/BedManager.java, server/catgenome/src/main/java/com/epam/catgenome/manager/gene/GffManager.java, server/catgenome/src/main/java/com/epam/catgenome/manager/vcf/VcfManager.java, server/catgenome/src/main/java/com/epam/catgenome/manager/vcf/reader/VcfFileReader.java, server/catgenome/src/main/java/com/epam/catgenome/manager/wig/reader/BedGraphReader.java, server/catgenome/src/main/java/com/epam/catgenome/util/Utils.java, server/catgenome/src/main/java/com/epam/catgenome/util/aws/S3Manager.java, server/catgenome/src/main/java/com/epam/catgenome/util/feature/reader/AbstractEnhancedFeatureReader.java, server/catgenome/src/main/java/com/epam/catgenome/util/feature/reader/EnhancedUrlHelper.java, server/catgenome/src/test/java/com/epam/catgenome/manager/gene/GffManagerUnitTest.java, server/catgenome/src/test/java/com/epam/catgenome/manager/tools/SortTest.java, server/catgenome/src/test/java/com/epam/catgenome/util/aws/S3ManagerTest.java
Support for AWS S3 URI enabled for tracks from URL (unregistered files): BAM, VCF, BED, GENE
This PR provides feature requested in issue #117 . Files from S3 buckets may be viewed using S3 URI, e.g. "s3://bucket/test.vcf.gz". This feature works for BAM, BED, VCF, GENE files opened via URL (non registered files). NGB server uses default AWS credentials to access S3 buckets, so make sure that you have them on NGB server instance.
For all files opened via URL a processing is applied: if URI scheme is s3://, URI is replaced with a singed S3 url. The matching AWS credentials must be enabled on NGB server to gain access to buckets.
- Install AWS credentials according to this [article](http://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html) on NGB server and upload files to …
=> Support for AWS S3 URI enabled for tracks from URL

docs/md/cli/command-reference.md, server/catgenome/src/main/java/com/epam/catgenome/manager/reference/ReferenceManager.java
Fix bug with error message during reference registration with species.
Add information about species version unicity to cli docs.
Added species version to error message.
1) Register reference with unregistered species: reg_ref /path/to/reference --species "unregistered_species" 
2) See error message containing unregistered version.
=> Fix error message

client/client/app/components/ngbBlatSearchPanel/ngbBlatSearch/ngbBlatSearch.controller.js, client/client/app/components/ngbTracksView/ngbTracksView.controller.js, client/client/app/shared/components/ngbGoldenLayout/ngbGoldenLayout.controller.js, client/client/app/shared/projectContext/index.js, client/client/modules/render/core/track/track.js, client/client/modules/render/core/viewport/viewport.js, client/client/modules/render/tracks/ruler/index.js, client/client/modules/render/tracks/ruler/rulerRenderer.js
Fix for #129 
Currently when user navigates to a region from the BLAT search results it is hard to find exact location of the found range.
This PR solves this. Found region is now highlighting within a local ruler space.
* Open BLAT search results
* Click on the row to navigate to a region
* Exact location of the found range should be highlighted within a local ruler.
=> Blat search resulting region highlighting

server/catgenome/src/main/java/com/epam/catgenome/util/feature/reader/EnhancedUrlHelper.java
Fix for opening AWS S3 paths in default (us-east-1) region
Currently NGB fails to open VCF, BED and GFF files from S3 buckets in default region (us-east-1). This PR introduces fix for this issue.
Regexp for matching s3 paths fixed
Upload VCF files to a bucket in us-east-1 region and upload VCF files. Check browsing VCF files from this bucket.
=> Fix for s3 paths handling in default region

server/catgenome/src/main/java/com/epam/catgenome/entity/BiologicalDataItemResourceType.java, server/catgenome/src/main/java/com/epam/catgenome/manager/FileManager.java, server/catgenome/src/main/java/com/epam/catgenome/manager/reference/ReferenceManager.java, server/catgenome/src/main/java/com/epam/catgenome/manager/reference/io/FastaUtils.java, server/catgenome/src/main/java/com/epam/catgenome/util/NgbFileUtils.java
This PR fixes issue #137 with opening Gene files (gtf, gff) using S3 paths
Currently gene files cannot be opened by S3 link, this PR fixes this problem.
- Upload gtf/gff file and corresponding index to S3 bucket.
- Check viewing uploaded files in NGB using S3 path, e.g. s3://bucket/genes.gtf.gz
=> Fix for issue #137 (browsing gene files via s3 paths)

client/client/app/assets/scss/md-components/md-list.scss, client/client/app/components/ngbProjectInfoPanel/ngbProjectInfo/ngbProjectSummary/ngbProjectSummary.scss
Fix for issue #100 
Names of files overlap when their length more than width of rectangle on main panel in case of multi BAM/VCF selection was fixed
Open files with names longer than width of rectangle on main panel in case of multi BAM/VCF selection
=> Fixed text strings overlap

client/client/app/shared/components/ngbVariantDetails/ngbVariantVisualizer/ngbVariantVisualizer.service.js, client/client/modules/render/variant-render/renderers/structural-variant-renderer.js
Fix for issue #154 
'getEmptyAffectedGenes' method updated - now it returns 'empty' transcript as well.
=> 'Error loading variant info' error fixed (for variations that out of gene)

client/client/app/components/ngbVariantPanel/ngbVariantPanel.tpl.html, client/client/app/shared/components/ngbVariantDetails/ngbVariantDetails.constant.js, client/client/app/shared/components/ngbVariantDetails/ngbVariantInfo/ngbVariantInfo.service.js
Fix for issue #136 
* Order of 'VISUALIZER' and 'INFO' tabs was changed
* Description field with full variation location info was added to 'INFO' tab
* choose dataset
* open variants panel
* push info icon to open variation info popup
* 'INFO' tab should be first in order and there should be Description field in it
=> Display full variation location in variation info

server/catgenome/src/main/java/com/epam/catgenome/manager/gene/reader/GffReader.java, server/catgenome/src/main/java/com/epam/catgenome/manager/gene/reader/GtfReader.java, server/catgenome/src/test/java/com/epam/catgenome/manager/GffManagerTest.java
This PR changes the calculation of exons count for collapse mode.
Based on task #139 . Exon count for collapsed genes was calculate wrong.
Calculation of exons count for gene in collapsed mode was removed (now will return null). Added test for collapse and non-collapse case.
=> Fix exons count for collapsed genes

server/catgenome/src/main/java/com/epam/catgenome/entity/bam/Read.java, server/catgenome/src/main/java/com/epam/catgenome/util/BamUtil.java, server/catgenome/src/test/java/com/epam/catgenome/controller/BamControllerTest.java, server/catgenome/src/test/java/com/epam/catgenome/manager/bam/BamManagerTest.java
This PR adds the server side feature for issue #155. 
Read Group ID (RG ID) was added to the Read creation for the BAM. If read group is null, empty string returns.
=> Add read group

docs/README.md, docs/mkdocs.yml
There is a typo in the documentation, "Aignments"
Aignments → Alignments
See the documentation
- [NA] Unit tests are provided
- [NA] Integration tests are provided (if CLI/API was changed)
=> Fix Alignments typo in documentation

client/client/app/shared/components/ngbMainToolbar/ngbOpenFile/ngbOpenFile.controller.js
Fixes for issue Rename the file in current session #166
Display only "filename" by default, not  the full URL
1. Open a file from the NGB server or via the URL
2. Check that the file name is displayed in a short form
=> Rename the file in current session #166

server/catgenome/src/main/java/com/epam/catgenome/entity/BiologicalDataItemResourceType.java, server/catgenome/src/test/java/com/epam/catgenome/manager/bam/BamManagerTest.java
Currently there is minor bug, that causes an error on opening BAM files via S3 paths
This PR fixes related bug and enables fully functional work of non registered BAM files from local server path, remote URL, S3 path.
- open non registered BAM file from server file system
- open non registered BAM file from remote URl (http, https, ftp)
- open non registered BAM file from S3 path
=> Fix for opening non registered local/s3/url BAM files

client/client/app/app.controller.js, client/client/app/shared/services/api.service.js, docs/md/user-guide/embedding-js.md
Fix for issue #194 
Additional API response was added, so now it's possible to determine the exact moment when NGB is ready to receive `postMessage`s.
Host app will receive following response:
```javascript
{
isSuccessful: true,
message: 'ready',
}
```
Follow the instructions for embedding NGB listed in [the documentation](https://github.com/epam/NGB/blob/js-api_ready-event/docs/md/user-guide/embedding-js.md), they was updated according to changes.
=> Js api ready event

client/client/app/shared/components/ngbMainSettings/ngbMainSettingsDlg/ngbMainSettingsDlg.tpl.html, client/client/dataServices/local/defaultData.js, client/client/modules/render/tracks/bam/internal/transformers/bamReadsCoverageTransformer.js
Fix for issue #193 
* Changed Allele Frequency threshold units from percentage to floating number (from 0.00 to 1.00)
* Changed highlighting logic:
Before was: "% of mismatches" <= "allele frequency threshold",
now became: "% of mismatches" >= "allele frequency threshold"
Try changing the corresponding setting and see how BAM's locuses' highlighting changes
=> Changing allele frequency threshold setting behaviour

.travis.yml, singularity/README.md, singularity/build_image.sh, singularity/ngb.singularity, singularity/setup_environment.sh
Implementation of #224 
Some of the users do not run docker infrastructure at all. Instead, singularity containers are encouraged to be used.
To support such use cases, NGB distribution now includes singularity image, built from the docker image.
Currently, this is implemented using standalone sh scripts and a docker is used to bootstrap singularity. We shall probably change this to:
- Use `gradle` to build image (in the same manner as docker, i.e. `buildSingularity` command)
- Create a separate singularity file, that will not rely on the docker daemon/image or  to be present
=> Singularity image build support for NGB

server/catgenome/src/main/java/com/epam/catgenome/manager/gene/GffManager.java
Small changes that allow to show histogram for a gene file that is located on S3 cloud
=> load histo when file is from S3

server/catgenome/build.gradle, server/catgenome/src/main/java/com/epam/catgenome/manager/wig/FacadeWigManager.java, server/catgenome/src/main/java/com/epam/catgenome/manager/wig/WigProcessor.java, server/catgenome/src/main/java/com/epam/catgenome/util/aws/SeekableS3Stream.java
Provides support for registering WIG files located on the S3 bucket according to the [issue comment](https://github.com/epam/NGB/issues/215#issuecomment-447840190).
The essential part that made this pull request possible is the fact that `NgbSeekableStreamFactory` performs self-registration in [htsjdk](https://github.com/samtools/htsjdk)'s `SeekableStreamFactory` singleton and provides support for S3 files seekable streams.
- Small change in `FacadeWigManager` to support S3 paths as well as regular file system paths.
- Migrate to the newest [big library](https://github.com/JetBrains-Research/big) api in `WigProcessor`.
- Few fixes in logging templates.
=> Add support for WIG files located on S3 bucket

server/ngb-cli/src/main/java/com/epam/ngb/cli/app/Application.java, server/ngb-cli/src/main/java/com/epam/ngb/cli/app/ApplicationOptions.java, server/ngb-cli/src/main/java/com/epam/ngb/cli/constants/MessageConstants.java, server/ngb-cli/src/main/java/com/epam/ngb/cli/entity/AclSecuredEntry.java, server/ngb-cli/src/main/java/com/epam/ngb/cli/entity/PermissionsContainer.java, server/ngb-cli/src/main/java/com/epam/ngb/cli/manager/command/handler/http/AbstractHTTPCommandHandler.java, server/ngb-cli/src/main/java/com/epam/ngb/cli/manager/command/handler/http/DatasetListHandler.java, server/ngb-cli/src/main/java/com/epam/ngb/cli/manager/command/handler/http/GrantPermissionHandler.java, server/ngb-cli/src/main/java/com/epam/ngb/cli/manager/command/handler/http/PrintPermissionsHelper.java, server/ngb-cli/src/main/java/com/epam/ngb/cli/manager/command/handler/http/SearchHandler.java, server/ngb-cli/src/test/java/com/epam/ngb/cli/AbstractCliTest.java, server/ngb-cli/src/test/java/com/epam/ngb/cli/TestDataProvider.java, server/ngb-cli/src/test/java/com/epam/ngb/cli/TestHttpServer.java, server/ngb-cli/src/test/java/com/epam/ngb/cli/manager/command/handler/http/DatasetListHandlerTest.java, server/ngb-cli/src/test/java/com/epam/ngb/cli/manager/command/handler/http/SearchHandlerTest.java
This PR provides permissions viewing in CLI described in issue https://github.com/epam/NGB/issues/218
Support ability for users to view what permissions are set for a specific object (`seach` and `list_dataset` commands)
- a new flag option `--permissions (-perm)` created. If that option is specified permissions for each object (dataset/file) will be printed. 
- create several users/roles
-  grant permissions for files/datasets
- run `ngb ld --permissions` 
- run `ngb s file_name --permissions`
=> RBAC: Support permissions viewing in CLI 

server/catgenome/profiles/dev/catgenome.properties, server/catgenome/src/main/java/com/epam/catgenome/constant/MessagesConstants.java, server/catgenome/src/main/java/com/epam/catgenome/controller/person/UserController.java, server/catgenome/src/main/java/com/epam/catgenome/dao/BiologicalDataItemDao.java, server/catgenome/src/main/java/com/epam/catgenome/dao/DaoHelper.java, server/catgenome/src/main/java/com/epam/catgenome/dao/user/UserDao.java, server/catgenome/src/main/java/com/epam/catgenome/entity/security/NgbSecurityGroup.java, server/catgenome/src/main/java/com/epam/catgenome/manager/user/UserManager.java, server/catgenome/src/main/java/com/epam/catgenome/manager/user/UserSecurityService.java, server/catgenome/src/main/java/com/epam/catgenome/security/acl/GrantPermissionManager.java, server/catgenome/src/main/java/com/epam/catgenome/security/acl/JdbcMutableAclServiceImpl.java, server/catgenome/src/main/java/com/epam/catgenome/security/saml/SAMLUserDetailsServiceImpl.java, server/catgenome/src/main/java/com/epam/catgenome/security/saml/SamlUserRegisterStrategy.java, server/catgenome/src/main/resources/catgenome-messages.properties, server/catgenome/src/main/resources/conf/catgenome/acl-dao.xml, server/catgenome/src/main/resources/conf/catgenome/dao/user-dao.xml, server/catgenome/src/test/java/com/epam/catgenome/dao/user/UserDaoTest.java
This PR provides SAML users auto-registration described in issue https://github.com/epam/NGB/issues/223
The property `saml.user.auto.create` ha been changed. The following value are available:  AUTO, EXPLICIT, EXPLICIT_GROUP
- AUTO - creates a new NGB user if not exists
- EXPLICIT - requires users pre-registration id database (performs by admin)
- EXPLICIT_GROUP -  requires specific groups pre-registration. If users SAML groups have no intersections with registered NGB security groups the authentication will be failed.
Also, a new API method `/group/find` added that loads all groups or groups by prefix
- set property `saml.user.auto.create=EXPLICIT_GROUP`
- register user with specific group and grant permissions for that group for some items (e.g. datasets)
- authenticate SAML user with …
=> RBAC: Support users auto-registration based on SAML groups

client/client/app/shared/components/ngbUserManagement/ngbUserManagementDlg/ngbUserManagementDlg.controller.js, client/client/app/shared/components/ngbUserManagement/ngbUserManagementDlg/ngbUserManagementDlg.scss, client/client/app/shared/components/ngbUserManagement/ngbUserManagementDlg/ngbUserManagementDlg.service.js
Class names like `ad-group` cause some info to be blocked by the AdBlock.
Refactored `ad-group` class to `domain-group`.
The AdBlock shouldn't block domain groups in the users' list anymore.
=> Refactored class names to avoid elements' blocking by the AdBlock
